### ISSUE TITLE
The variabele scheme_id in AtramhasisProvider is used before the variabele is defined.

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/skosprovider_atramhasis#106]
Using `self.scheme_id` we define a variabele `metadata['uri']` in
https://github.com/OnroerendErfgoed/skosprovider_atramhasis/blob/79c55ab2fa7bc1d9ef1246b284757a9baca74264/skosprovider_atramhasis/providers.py#L54

The variabele `self.scheme_id` itself however is only defined later on in https://github.com/OnroerendErfgoed/skosprovider_atramhasis/blob/79c55ab2fa7bc1d9ef1246b284757a9baca74264/skosprovider_atramhasis/providers.py#L65

The order of those 2 statements should be reversed. If we use 2 AtramhasisProvider objects without explicity setting a uri, we will encounter following Exception:
`skosprovider.registry.RegistryException: A provider with URI None/conceptschemes/None has already been registered`

**Comment by Wim-De-Clercq** [comment]
We zullen dit ticket gebruiken om https://github.com/OnroerendErfgoed/skosprovider_atramhasis/pull/103#issuecomment-775874238 te doen.

**Comment by goessebr** [comment]
Is gereleased: https://github.com/OnroerendErfgoed/skosprovider_atramhasis/releases/tag/0.4.1 en staat ook op pypi
