### ISSUE TITLE
safteycheck in #9: what do we return?

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/skosprovider_atramhasis#11]
refering to #9 : do we raise an exception if the safety check fails, or do we just return False?

For safety, you should check if json.concept_scheme.id is equal to the provider's own ID. Otherwise, Atramhasis is returning a uri for a concept in a different provider than the one we're using.

**Comment by koenedaele** [comment]
I think the current solution is good. In the end, we find a concept or collection, but it's one that should not be serverd by that instance of AtramhasisProvider, so False is appropriate since there's no concept with that URI in this provider.
