### ISSUE TITLE
refering to #8: what happens if a conceptscheme is not found?

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/skosprovider_atramhasis#12]
I have written a method that gets the conceptscheme (refering #8). What do we do if the schem_id is not found? Exception? or can we handle this in a better way?

**Comment by koenedaele** [comment]
If the conceptscheme can't be found, then the scheme_id is either wrong or the service is unavailable. The second case is handled by the ProviderUnavailableException.

So, this is not a runtime, but a configuration issue. Not sure if there's a good exception for that. Should something like that be added to skosprovider?

For 0.1.0, I'm ok with going with a regular Exception.

**Comment by koenedaele** [comment]
Fixed together with #58
