### ISSUE TITLE
handling languages in skosprovider_atramhasis

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/skosprovider_atramhasis#2]
how can we get labels in different languages based on pyramid_skosprovider. Currently the label is used that atramhasis services returns (without language support)

**Comment by koenedaele** [comment]
Good question. I'm assuming this is a problem with the lists based responses (find, get_all, top_concepts, ...) and not with the id based response (get by id)?

**Comment by dieuska** [comment]
Indeed. The implementation of'get_by_id' requests the full concept (json-formatted) so you have labels in all languages and a Concept-object is returned.
The problem raises when using  lists based responses in the implementation (find, get_all, top_concepts, ...) because they have no language parameter. You only get a list-response with one label...

**Comment by koenedaele** [comment]
This requires some fixes in pyramid_skosprovider.

I think we might need to do 2 things:

 * Make sure that pyramid_skosprovider honors the current request locale, like here in Atramhasis: https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/views/views.py#L156 Is this something standard to pyramid or is this something we made up for Atramhasis?
 * Make it possible to override the current request locale with a parmeter in the url. eg /conceptschemes/STYLES/c?language=nl-BE.

/cc @BartSaelen

**Comment by koenedaele** [comment]
Discussion moved to koenedaele/pyramid_skosprovider#10 since that's where it belongs.
