### ISSUE TITLE
upgraden dogpile.cache==1.1.1

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/skosprovider_atramhasis#95]
Komt uit https://github.com/onroerenderfgoed/inventaris/issues/4020

Er is een code change nodig, dogpile.util.compat.string_type wordt niet gevonden,
zie testen https://github.com/OnroerendErfgoed/inventaris/pull/4025
![image](https://user-images.githubusercontent.com/1926276/104423909-f6d00400-557e-11eb-9c3c-dbb77d44864a.png)

**Comment by koenedaele** [comment]
See #96 : Drop support for python 2
